// Writes src/api/openapi.gen.ts: the OpenAPI document as a string constant, so the Worker
// serves it without rebuilding it from the zod schemas on each request (H2 measurement).
// Run after changing any route: pnpm --filter @clavis/worker openapi
import { writeFileSync } from 'node:fs';
import { buildApi, OPENAPI_CONFIG } from '../src/api/index';

const doc = buildApi().getOpenAPI31Document(OPENAPI_CONFIG);
const out = new URL('../src/api/openapi.gen.ts', import.meta.url);
writeFileSync(
  out,
  `// Generated by scripts/openapi.ts — do not edit. test/openapi.test.ts checks it is current.\nexport const OPENAPI_JSON = ${JSON.stringify(JSON.stringify(doc))};\n`,
);
console.log(`wrote ${out.pathname} (${Object.keys(doc.paths ?? {}).length} paths)`);
