/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SKeyIndexRouteImport } from './routes/s.$key.index'
import { Route as SKeyHealthRouteImport } from './routes/s.$key.health'
import { Route as SKeyNewRouteImport } from './routes/s.$key.new'
import { Route as SKeyTrashRouteImport } from './routes/s.$key.trash'
import { Route as SKeyPSlugIdRouteImport } from './routes/s.$key.p.$slugId'
import { Route as SKeyWTitleRouteImport } from './routes/s.$key.w.$title'
import { Route as SKeyPSlugIdEditRouteImport } from './routes/s.$key.p.$slugId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SKeyIndexRoute = SKeyIndexRouteImport.update({
  id: '/s/$key/',
  path: '/s/$key/',
  getParentRoute: () => rootRouteImport,
} as any)
const SKeyHealthRoute = SKeyHealthRouteImport.update({
  id: '/s/$key/health',
  path: '/s/$key/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SKeyNewRoute = SKeyNewRouteImport.update({
  id: '/s/$key/new',
  path: '/s/$key/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SKeyTrashRoute = SKeyTrashRouteImport.update({
  id: '/s/$key/trash',
  path: '/s/$key/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SKeyPSlugIdRoute = SKeyPSlugIdRouteImport.update({
  id: '/s/$key/p/$slugId',
  path: '/s/$key/p/$slugId',
  getParentRoute: () => rootRouteImport,
} as any)
const SKeyWTitleRoute = SKeyWTitleRouteImport.update({
  id: '/s/$key/w/$title',
  path: '/s/$key/w/$title',
  getParentRoute: () => rootRouteImport,
} as any)
const SKeyPSlugIdEditRoute = SKeyPSlugIdEditRouteImport.update({
  id: '/s/$key/p/$slugId_/edit',
  path: '/s/$key/p/$slugId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/s/$key/health': typeof SKeyHealthRoute
  '/s/$key/new': typeof SKeyNewRoute
  '/s/$key/trash': typeof SKeyTrashRoute
  '/s/$key/': typeof SKeyIndexRoute
  '/s/$key/p/$slugId': typeof SKeyPSlugIdRoute
  '/s/$key/w/$title': typeof SKeyWTitleRoute
  '/s/$key/p/$slugId/edit': typeof SKeyPSlugIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/s/$key/health': typeof SKeyHealthRoute
  '/s/$key/new': typeof SKeyNewRoute
  '/s/$key/trash': typeof SKeyTrashRoute
  '/s/$key': typeof SKeyIndexRoute
  '/s/$key/p/$slugId': typeof SKeyPSlugIdRoute
  '/s/$key/w/$title': typeof SKeyWTitleRoute
  '/s/$key/p/$slugId/edit': typeof SKeyPSlugIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/s/$key/health': typeof SKeyHealthRoute
  '/s/$key/new': typeof SKeyNewRoute
  '/s/$key/trash': typeof SKeyTrashRoute
  '/s/$key/': typeof SKeyIndexRoute
  '/s/$key/p/$slugId': typeof SKeyPSlugIdRoute
  '/s/$key/w/$title': typeof SKeyWTitleRoute
  '/s/$key/p/$slugId_/edit': typeof SKeyPSlugIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/search'
    | '/s/$key/health'
    | '/s/$key/new'
    | '/s/$key/trash'
    | '/s/$key/'
    | '/s/$key/p/$slugId'
    | '/s/$key/w/$title'
    | '/s/$key/p/$slugId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/search'
    | '/s/$key/health'
    | '/s/$key/new'
    | '/s/$key/trash'
    | '/s/$key'
    | '/s/$key/p/$slugId'
    | '/s/$key/w/$title'
    | '/s/$key/p/$slugId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/search'
    | '/s/$key/health'
    | '/s/$key/new'
    | '/s/$key/trash'
    | '/s/$key/'
    | '/s/$key/p/$slugId'
    | '/s/$key/w/$title'
    | '/s/$key/p/$slugId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SearchRoute: typeof SearchRoute
  SKeyHealthRoute: typeof SKeyHealthRoute
  SKeyNewRoute: typeof SKeyNewRoute
  SKeyTrashRoute: typeof SKeyTrashRoute
  SKeyIndexRoute: typeof SKeyIndexRoute
  SKeyPSlugIdRoute: typeof SKeyPSlugIdRoute
  SKeyWTitleRoute: typeof SKeyWTitleRoute
  SKeyPSlugIdEditRoute: typeof SKeyPSlugIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$key/': {
      id: '/s/$key/'
      path: '/s/$key'
      fullPath: '/s/$key/'
      preLoaderRoute: typeof SKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$key/health': {
      id: '/s/$key/health'
      path: '/s/$key/health'
      fullPath: '/s/$key/health'
      preLoaderRoute: typeof SKeyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$key/new': {
      id: '/s/$key/new'
      path: '/s/$key/new'
      fullPath: '/s/$key/new'
      preLoaderRoute: typeof SKeyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$key/trash': {
      id: '/s/$key/trash'
      path: '/s/$key/trash'
      fullPath: '/s/$key/trash'
      preLoaderRoute: typeof SKeyTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$key/p/$slugId': {
      id: '/s/$key/p/$slugId'
      path: '/s/$key/p/$slugId'
      fullPath: '/s/$key/p/$slugId'
      preLoaderRoute: typeof SKeyPSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$key/w/$title': {
      id: '/s/$key/w/$title'
      path: '/s/$key/w/$title'
      fullPath: '/s/$key/w/$title'
      preLoaderRoute: typeof SKeyWTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$key/p/$slugId_/edit': {
      id: '/s/$key/p/$slugId_/edit'
      path: '/s/$key/p/$slugId/edit'
      fullPath: '/s/$key/p/$slugId/edit'
      preLoaderRoute: typeof SKeyPSlugIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SearchRoute: SearchRoute,
  SKeyHealthRoute: SKeyHealthRoute,
  SKeyNewRoute: SKeyNewRoute,
  SKeyTrashRoute: SKeyTrashRoute,
  SKeyIndexRoute: SKeyIndexRoute,
  SKeyPSlugIdRoute: SKeyPSlugIdRoute,
  SKeyWTitleRoute: SKeyWTitleRoute,
  SKeyPSlugIdEditRoute: SKeyPSlugIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
