SELECT 'Q1 3자 한글(결제 A)' AS q, group_concat(p.id) AS hits FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"결제 A"';
SELECT 'Q2 3자 한글(데이터)', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"데이터"';
SELECT 'Q3 4자 복합어 부분(리팩터)', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"리팩터"';
SELECT 'Q4 2자 한글(결제) MATCH', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"결제"';
SELECT 'Q5 2자 한글(결제) LIKE on FTS', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE f.content LIKE '%결제%' OR f.title LIKE '%결제%';
SELECT 'Q6 영문 대소문자(postgresql)', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"postgresql"';
SELECT 'Q7 띄어쓰기 다름(부분 환불)', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"부분 환불"';
SELECT 'Q8 AND 두 단어(결제모 AND 리팩)', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"결제모" AND "리팩터"';
SELECT 'Q9 제목 컬럼 한정(title:환불 정)', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH 'title:"환불 정"';
SELECT 'Q10 frontmatter 검색(owner: toby)', group_concat(p.id) FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"owner: toby"';
SELECT 'Q11 snippet', snippet(s1_fts, 1, '<b>', '</b>', '…', 8) FROM s1_fts WHERE s1_fts MATCH '"비동기"';
SELECT 'Q12 bm25 rank', group_concat(id) FROM (SELECT p.id FROM s1_fts f JOIN s1_pages p ON p.rowid=f.rowid WHERE s1_fts MATCH '"결제 "' ORDER BY bm25(s1_fts, 10.0, 1.0));
UPDATE s1_pages SET content = '## 개요\n정산 배치를 설계한다.' WHERE id='p1';
SELECT 'Q13 update 후 옛 내용(비동기)', count(*) FROM s1_fts WHERE s1_fts MATCH '"비동기"';
SELECT 'Q14 update 후 새 내용(정산 배)', count(*) FROM s1_fts WHERE s1_fts MATCH '"정산 배"';
DELETE FROM s1_pages WHERE id='p2';
SELECT 'Q15 delete 후(환불 정)', count(*) FROM s1_fts WHERE s1_fts MATCH '"환불 정"';
INSERT INTO s1_fts(s1_fts) VALUES ('rebuild');
SELECT 'Q16 rebuild 후(정산 배)', count(*) FROM s1_fts WHERE s1_fts MATCH '"정산 배"';
INSERT INTO s1_fts(s1_fts) VALUES ('integrity-check');
SELECT 'Q17 integrity-check', 'ok';
